POST http://localhost:3000/employee-api/employee
Content-Type: application/json

{
    "firstName":"sravs",
    "lastName":"gunna",
    "email":"srav@gmail.com",
    "mobile":2345678901,
    "designation":"sde",
    "company":"xxx"
}
###


GET http://localhost:3000/employee-api/employees
###

PUT http://localhost:3000/employee-api/employee/69ca2c1269d9bafc535961e3
Content-Type: application/json

{
    "firstName":"sravs",
    "lastName":"gunna",
    "email":"srav@gmail.com",
    "mobile":2345678901,
    "designation":"sde",
    "company":"xxx"
};
###

DELETE http://localhost:3000/employee-api/employee/69ca2c1269d9bafc535961e3